name: Push components to Espressif Component Service

on:
  push:
    branches:
      - master

jobs:
  upload_components_custom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: "recursive"
      - name: check server connection
        run: |
          curl ${{ secrets.API_ENDPOINT }} | grep "Espressif Component Manager"
      - name: install dependencies
        run: |
          pip install idf-component-manager
      - name: test file location
        run: |
          which python
          python -c "import idf_component_manager; print(idf_component_manager.__file__)"
      - name: upload
        run: |
          export COMPONENTS_DIRECTORIES="components/test_comp;components/test_comp2"
          export COMPONENTS_NAMESPACE="espressif"
          export IDF_COMPONENT_API_TOKEN="${{ secrets.IDF_COMPONENT_API_TOKEN }}"
          bash upload.sh
